lib/searchsearch.go
only thoroughly checked the docs/code, not sure if it's supported yet
reference:
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-request-search-type.html
which is useful when:
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-aggregations.html#_returning_only_aggregation_results
may also add AggregationOnly() for more convenience
=> add support for search_type argument

lib/coretest_test.go
LoadTestData creates its own connection and previously ignored the -host argument. Easy fix. :beers:
=> LoadTestData obeys -host argument

lib/clusternodesinfo.go, lib/indicesopencloseindex.go
The current version doesn't work for close and open all indices. (API change I guess, you need to use _all in a explicit way)
This patch fix the problem with two function OpenIndices and CloseIndices
=> Open close indices

lib/indicescreateindex.go
Writing settings parameter as struct can be unreadable, shown as below
```go
CreateIndexWithSettings("index_name", struct {
Settings map[string]interface{} `json:"settings"`
}{
Settings: map[string]interface{}{
"index" : map[string]int{//...},
"analysis": map[string]interface{}{
// some other string-interface maps and maps
},
},
})
```
map makes our life easier right here :) i allowed struct type for backward. i don't examine yet other methods, if i meet like this, i will handle. thanks
=> allowed map type for settings param of CreateIndexWithSettings

lib/indicesputmapping.go, lib/indicesputmapping_test.go
"Fix" for Issue #176. Added a function that takes []byte as parameter for the mapping. Allows for simple usage without the need of struct instance of MappingOptions
Provides no validation.
=> Added PutMappingFromJSON and test for it

lib/searchaggregate.go, lib/searchaggregate_test.go
ElasticSearch has default query result size limitation 10 if size field is not provided. And if size is 0, the size of result is unlimited.
If I query using this function with size 0, the `omitempty` option will prune out `size` field and trying get result with default size limitation 10.
This change can prevent the situation above.
=> Change FieldAggregate.Size type to *int

lib/searchquery.go
This lets you search for a single term against multiple fields:
```
elastigo.Query().MultiMatch("fish", []string{"title", "description"}) 
```
=> Add support for multi-match queries in the dsl

lib/searchfilter.go
The bool filter already existed, but wasn't exposed, so it always defaulted to "and".
=> Add setter method for boolean filter in dsl

lib/searchquery.go
Example:
```
linear := map[string]interface{}{
"linear": map[string]interface{}{
"created_at": map[string]interface{}{
"decay":  0.1,
"offset": "1d",
"origin": "now",
"scale":  "2w",
},
},
}
script := map[string]interface{}{
"script_score": map[string]interface{}{
"script": "doc['likes'].value*5 + doc['plays'].value*2",
},
}
q := elastigo.Query().FunctionScore("multiply", linear, script)
```
=> Add support for function score on query dsl

lib/corebulk.go
Needed a quick fix for using scripts in bulk updates. Works with the following test but let me know if you want me to add something to corebulk_test.go
```
func TestElasticScript(t *testing.T) {
indexer := elastic.Conn.NewBulkIndexerErrors(ElasticMaxConns, 2)
defer elastic.Conn.DeleteIndex("twitter")
done := make(chan struct{}, 1)
defer close(done)
go func() {
for {
select {
case err := <-indexer.ErrorChannel:
t.Error(err)
case <-done:
return
}
}
}()
indexer.Start()
indexer.Index("twitter", "user", "10", "", nil, `{"name":"bob","val":15}`, true)
time.Sleep(time.Millisecond * 10)
indexer.Stop()
indexer.Start()
tm := time.Now().UTC()
indexer.UpdateWithWithScript(
"twitter", // index
"user",    // type
"10",      // id
"",        // ttl
&tm,       // time
"ctx._source.val+=20", //script …
```
=> adding helper for bulk update with script

lib/connection.go, lib/connection_test.go
This adds a small convenience function to allow connections to be set up from a URL instead of specifying connection properties separately. 
Many cloud-based providers of Elasticsearch provide you with connection strings as URLs. For instance, if you use Heroku and add Searchbox (Elasticsearch as a service) to your app, the Searchbox connection URL is automatically added to your Heroku app config. The SetFromUrl function will enable easy configuration by letting you to pass in the config value directly.
Is this of any value?
=> Added SetFromUrl function to connection

lib/corebulk.go
Insert a milli-sleep after Stop() has been called to let other goros set the buffer before flushing. Without this, a quick (faster than the timer), small (smaller than the max size) bulk write will never actually be sent, as when Flush() is called, the docCount is errantly 0. 
A "better" way to solve it is with a semaphore, but that's more invasive than I care to get at the moment, as a 2milli sleep suffices.
Example code
c := elastigo.NewConn()
indexer := c.NewBulkIndexerErrors(10, 60)
indexer.Start()
indexer.Index("twitter", "user", "1", "", nil, `{"name":"bob"}`, true)
indexer.Stop()
=> BulkIndexing Fix

lib/catresponses.go
Fixes #208 Using this in an application that requires the name and status of the index.
=> added status field to CatIndexInfo struct

lib/indicesputmapping.go, lib/indicesputmapping_test.go
add support for _ttl mapping field when using the MappingOptions struct to define a mapping
=> Support TTL in MappingOptions

lib/corepercolate.go, lib/corepercolate_test.go
Currently, the existing `Match` struct does not comply
with json returned from a percolate query.
This fixes that.
Example percolate response as of ES 1.6.0:
```json
{"took":9,"_shards":{"total":3,"successful":3,"failed":0},"total":3,
"matches":[{"_index":"test-geoevents-20150706-115234","_id":"nyc,West Village"},{"_index":"test-geoevents-20150706-115234","_id":"nyc,Manhattan"},{"_index":"test-geoevents-20150706-115234","_id":"nyc,Greenwich Village"}]}
```
=> Update Percolate to unmarshal response into a valid struct

lib/corebulk.go
According to the doc from [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html),  `retry_on_conflict` can't be use anymore, once use it, `elasticsearch 1.7.1` will raise a error follows, and change `retry_on_conflict` to `_retry_on_conflict ` can fix it.
```
bulkIndexer: &{2015-08-24 17:54:24.32818233 +0800 CST: Error [IllegalArgumentException[Action/metadata line [1] contains an unknown parameter [retry_on_conflict]]] Status [500] [500] }
```
=> bulk api is not consistent with api doc

lib/corebulk.go, lib/corebulk_test.go, lib/coreexample_test.go, lib/coretest_test.go
This commit moves the refresh property to be
an attribute of the BulkIndexer struct.
The refresh attribute is included as a query param
when the request is sent to the Elasticsearch API.
=> remove refresh from action/meta. fixes #215

lib/request.go, lib/request_test.go
The current implementation of Escape fails for many of the types in the type switch. This change allows all types of ints and floats to be used.
Tests are added to check against these conditions.
This fixes passes the tests using `go test *.go -test.run=TestQuery`
=> Fixed Escape to handle int32, int64, and float32

lib/corebulk.go
This patch ensures the ticker gets stopped when shutdown is called on a BulkIndexer to prevent memory leaks.
=> Explicitly stop ticker to avoid memory leaks

lib/corebulk.go
If the message buffer has been read, the buffer sent through the ErrorChannel will be empty. This pull request copies the buffer back from the bufCopy used for retries.
=> Send an unread Buffer to the ErrorChannel

lib/coresearch.go
If `sort` field is present in the search request, Elastic will add the sort value for each hit record.
https://www.elastic.co/guide/en/elasticsearch/guide/current/_sorting.html
These values should be parsed in order to avoid parsing response twice to get them.
=> Parse `sort` field in search results

lib/baserequest.go, lib/connection.go, lib/request.go, lib/request_test.go
Adds Gzip support for requests, really useful for saving bandwidth with bulk requests.
=> Add gzip/compression support

lib/searchsearch.go, lib/searchsearch_test.go
This is different from the Fields methods as ElasticSearch will return a _source with only the fields specified.
It is a quick attempt to fix my needs. If I miss something, just tell me what I should change and I will =)
Also, I didn't add tests as the normal Source method doesn't have one.
Thanks for the lib.
=> Adds source filtering for SearchDsl

lib/coresearch.go
This adds the `_ttl` key to hits and properly parses it into a `time.Time` from the Elasticsearch formatting, milliseconds in the future that the document will expire.
=> Add support for the _ttl key in a hit
